apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-depl
  labels:
    app: nginx-depl

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-depl
  template:
    metadata:
      labels:
        app: nginx-depl
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
